# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98bf0afcec713263682c457faf5a08fd28ddbcd37ea26736955fc563d7070d7a48b8ddd6a2186e07f9d897d594cbae381f623ce9a7a0a129a2e4d8b5e1eca59f

test:
  secret_key_base: 0ee63ea4f2d989762570571f3cee755960ca2506e494a1804cf9f098a45430abb35520583755dcc9ac8c60b119f76b2e9e23deb83df75fb87bfdea065191ea45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
